---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: kube-system
spec:
  releaseName: external-secrets
  chart:
    spec:
      chart: external-secrets
      version: 0.12.1
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  interval: 10m
  timeout: 5m
  install:
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
