---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-pool
  namespace: kube-system
spec:
  addresses:
    - 192.168.20.200-192.168.20.210
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-advertisment
  namespace: kube-system
spec:
  ipAddressPools:
    - metallb-pool
