---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-vip
  namespace: kube-system
spec:
  releaseName: kube-vip
  chart:
    spec:
      chart: kube-vip
      version: 0.6.4
      sourceRef:
        kind: HelmRepository
        name: kube-vip
        namespace: flux-system
  interval: 10m
  timeout: 5m
  install:
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
